"""
try, except - tratando exceções em python
"""

try:
    print(a)
except NameError as erro:
    print('erro desconhecido1')

